# Generated by Django 5.0.6 on 2024-06-13 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_cardealer_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='color',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='car_model',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
