# Generated by Django 5.0.6 on 2024-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0003_remove_vehicles_color_vehicles_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
